### ISSUE TITLE
Wont launch

### ISSUE THREAD

**Issue by thedude1987** [M4elstr0m/TarkovMapTracker#1]
I have tried everything to get this thing to launch. I get the black terminal screen flash everytime i double click the batch file and thats it.

**Comment by M4elstr0m** [comment]
Hello @thedude1987 I'm really sorry I did'nt see your comment! 
Can you try to open the command line first to execute the batch so that we can see any errors?

Here's the detailed steps:

1. **Go in your folder where the .bat file is located**
2. **Shift+Right Click** in this folder and select **"Open Powershell terminal here"**
3. When the terminal show up, execute this command in Powershell : `./Start.bat`

Then if there's any errors please _paste them here_ so I can help you more precisely, and if the script works when you do that using powershell I will help you to automatize everything

**Comment by cjans1130** [comment]
I am having the same issue. I followed your steps and I get this error:
![image](https://github.com/user-attachments/assets/0bb81b84-f637-4d91-bd75-1a54cca7055a)

**Comment by M4elstr0m** [comment]
> I am having the same issue. I followed your steps and I get this error: (image)
@cjans1130 
It seems your Powershell window is open in the **wrong directory** : **you have to be in the same folder as the Start.bat** so not in "tarkov-map-tracker". 
For example for your computer it seems the path would be "C:\Users\cjans\Desktop\TarkovMapTracker-main\TarkovMapTracker-main\"
Be sure that the Start.bat is located in the main folder (_you don't have to go in 'tarkov-map-tracker' folder using the Start.bat way_)

**Comment by M4elstr0m** [comment]
You have to do "pip install tk" in a Powershell window, I'll update the script soon in order to do it automatically

**Comment by M4elstr0m** [comment]
For everyone getting a missing package error, and @Fuckingnameless : **Download the new repository (I just updated it) and type the command "pip install -r requirements.txt" in your main folder, every requirements will be downloaded automatically**

**Comment by sillyman6** [comment]
Hello i am experiencing the same issue as the first person, except that when entering ./Start.bat into the power shell in the folder no text appears afterwards 
![image](https://github.com/user-attachments/assets/ec6d3135-e07b-4844-9eef-4b601d93bcfc)
and i see a software open and immediately close at the bottom.

**Comment by M4elstr0m** [comment]
> > For everyone getting a missing package error, and @Fuckingnameless : **Download the new repository (I just updated it) and type the command "pip install -r requirements.txt" in your main folder, every requirements will be downloaded automatically** If the software works, don't hesitate to leave a star on this repository ;) support is always appreciated
> 
> Thanks for the prompt reply and fix, should have been obvious but windows dumbs me down lol will try asap, do you know if this works in SPTarkov?

@Fuckingnameless 
Well if you can do a screenshot like in Tarkov, and if the maps are the same, it should ;) Please tell me if it works (I did'nt tried SPTarkov)

**Comment by M4elstr0m** [comment]
> Hello i am experiencing the same issue as the first person, except that when entering ./Start.bat into the power shell in the folder no text appears afterwards ![image](https://private-user-images.githubusercontent.com/180242411/363825008-ec6d3135-e07b-4844-9eef-4b601d93bcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzAzMzMsIm5iZiI6MTcyNTM3MDAzMywicGF0aCI6Ii8xODAyNDI0MTEvMzYzODI1MDA4LWVjNmQzMTM1LWUwN2ItNDg0NC05ZWVmLTRiNjAxZDkzYmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGM1ZTFmOTMwZDBhMmEwYjJjOWFjZGRmNTkzYzJlMjgyNmE0MmEzOWM3OGQ2NjY1M2ZiOGRhNzlhZTBmM2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FgmjXM9zoDNEr4rjPJlnNl3EjMx7K8Hp5nySldReiQA) and i see a software open and immediately close at the bottom.

Okay first I'll have to find the cause of the issue, did you try the command "pip install -r requirements.txt" aswell? Maybe all of those issues are because of missing packages?

**Comment by sillyman6** [comment]
> > Hello i am experiencing the same issue as the first person, except that when entering ./Start.bat into the power shell in the folder no text appears afterwards ![image](https://private-user-images.githubusercontent.com/180242411/363825008-ec6d3135-e07b-4844-9eef-4b601d93bcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzAzMzMsIm5iZiI6MTcyNTM3MDAzMywicGF0aCI6Ii8xODAyNDI0MTEvMzYzODI1MDA4LWVjNmQzMTM1LWUwN2ItNDg0NC05ZWVmLTRiNjAxZDkzYmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGM1ZTFmOTMwZDBhMmEwYjJjOWFjZGRmNTkzYzJlMjgyNmE0MmEzOWM3OGQ2NjY1M2ZiOGRhNzlhZTBmM2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FgmjXM9zoDNEr4rjPJlnNl3EjMx7K8Hp5nySldReiQA) and i see a software open and immediately close at the bottom.
> 
> Okay first I'll have to find the cause of the issue, did you try the command "pip install -r requirements.txt" aswell? Maybe all of those issues are because of missing packages?

This is what appears when typing pip install -r requirements.txt
![image](https://github.com/user-attachments/assets/95500453-a799-46f1-b029-7156cdad7233)

**Comment by M4elstr0m** [comment]
> > > Hello i am experiencing the same issue as the first person, except that when entering ./Start.bat into the power shell in the folder no text appears afterwards ![image](https://private-user-images.githubusercontent.com/180242411/363825008-ec6d3135-e07b-4844-9eef-4b601d93bcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzAzMzMsIm5iZiI6MTcyNTM3MDAzMywicGF0aCI6Ii8xODAyNDI0MTEvMzYzODI1MDA4LWVjNmQzMTM1LWUwN2ItNDg0NC05ZWVmLTRiNjAxZDkzYmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGM1ZTFmOTMwZDBhMmEwYjJjOWFjZGRmNTkzYzJlMjgyNmE0MmEzOWM3OGQ2NjY1M2ZiOGRhNzlhZTBmM2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FgmjXM9zoDNEr4rjPJlnNl3EjMx7K8Hp5nySldReiQA) and i see a software open and immediately close at the bottom.
> > 
> > 
> > Okay first I'll have to find the cause of the issue, did you try the command "pip install -r requirements.txt" aswell? Maybe all of those issues are because of missing packages?
> 
> This is what appears when typing pip install -r requirements.txt ![image](https://private-user-images.githubusercontent.com/180242411/364067454-95500453-a799-46f1-b029-7156cdad7233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTEyMTgsIm5iZiI6MTcyNTQ1MDkxOCwicGF0aCI6Ii8xODAyNDI0MTEvMzY0MDY3NDU0LTk1NTAwNDUzLWE3OTktNDZmMS1iMDI5LTcxNTZjZGFkNzIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMTU1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDA5OWIyMGE3ZWU1ZGYxZTE4MzM0M2RjNzMyYmY1N2E2OThhYjE0YzFhYTQxYWQ4YTdmN2VlMDYzNTRmNzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CBAFnxHzVVmpYlwXy10WBAADtG5n31l5NV9yNorK89c)

**Perfect! thank you exactly what we needed to solve the issue!**
Well it seems my script isn't the problem here: to solve your problem, **you have to install pip first**, it usually comes with last version of python (you also have to install python if you didn't do it yet of course) but you still can download it if you already have python installed **with the following command**: `py -m ensurepip --upgrade` 
Notice that on some Operating system it might be `python -m ensurepip --upgrade` or even `python3 -m ensurepip --upgrade`
Please tell me if it works ;)

**Comment by sillyman6** [comment]
> > > > Hello i am experiencing the same issue as the first person, except that when entering ./Start.bat into the power shell in the folder no text appears afterwards ![image](https://private-user-images.githubusercontent.com/180242411/363825008-ec6d3135-e07b-4844-9eef-4b601d93bcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzAzMzMsIm5iZiI6MTcyNTM3MDAzMywicGF0aCI6Ii8xODAyNDI0MTEvMzYzODI1MDA4LWVjNmQzMTM1LWUwN2ItNDg0NC05ZWVmLTRiNjAxZDkzYmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGM1ZTFmOTMwZDBhMmEwYjJjOWFjZGRmNTkzYzJlMjgyNmE0MmEzOWM3OGQ2NjY1M2ZiOGRhNzlhZTBmM2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FgmjXM9zoDNEr4rjPJlnNl3EjMx7K8Hp5nySldReiQA) and i see a software open and immediately close at the bottom.
> > > 
> > > 
> > > Okay first I'll have to find the cause of the issue, did you try the command "pip install -r requirements.txt" aswell? Maybe all of those issues are because of missing packages?
> > 
> > 
> > This is what appears when typing pip install -r requirements.txt ![image](https://private-user-images.githubusercontent.com/180242411/364067454-95500453-a799-46f1-b029-7156cdad7233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTEyMTgsIm5iZiI6MTcyNTQ1MDkxOCwicGF0aCI6Ii8xODAyNDI0MTEvMzY0MDY3NDU0LTk1NTAwNDUzLWE3OTktNDZmMS1iMDI5LTcxNTZjZGFkNzIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMTU1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDA5OWIyMGE3ZWU1ZGYxZTE4MzM0M2RjNzMyYmY1N2E2OThhYjE0YzFhYTQxYWQ4YTdmN2VlMDYzNTRmNzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CBAFnxHzVVmpYlwXy10WBAADtG5n31l5NV9yNorK89c)
> 
> **Perfect! thank you exactly what we needed to solve the issue!** Well it seems my script isn't the problem here: to solve your problem, **you have to install pip first**, it usually comes with last version of python (you also have to install python if you didn't do it yet of course) but you still can download it if you already have python installed **with the following command**: `py -m ensurepip --upgrade` Notice that on some Operating system it might be `python -m ensurepip --upgrade` or even `python3 -m ensurepip --upgrade` Please tell me if it works ;)

i have successfully installed all of the related requirements yet it still instantly closes when doing ./Start.bat 
![image](https://github.com/user-attachments/assets/8a418a18-af45-4918-a4db-bed11f0a14d2) Perhaps there is another issue?

**Comment by M4elstr0m** [comment]
> > > > > Hello i am experiencing the same issue as the first person, except that when entering ./Start.bat into the power shell in the folder no text appears afterwards ![image](https://private-user-images.githubusercontent.com/180242411/363825008-ec6d3135-e07b-4844-9eef-4b601d93bcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzAzMzMsIm5iZiI6MTcyNTM3MDAzMywicGF0aCI6Ii8xODAyNDI0MTEvMzYzODI1MDA4LWVjNmQzMTM1LWUwN2ItNDg0NC05ZWVmLTRiNjAxZDkzYmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGM1ZTFmOTMwZDBhMmEwYjJjOWFjZGRmNTkzYzJlMjgyNmE0MmEzOWM3OGQ2NjY1M2ZiOGRhNzlhZTBmM2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FgmjXM9zoDNEr4rjPJlnNl3EjMx7K8Hp5nySldReiQA) and i see a software open and immediately close at the bottom.
> > > > 
> > > > 
> > > > Okay first I'll have to find the cause of the issue, did you try the command "pip install -r requirements.txt" aswell? Maybe all of those issues are because of missing packages?
> > > 
> > > 
> > > This is what appears when typing pip install -r requirements.txt ![image](https://private-user-images.githubusercontent.com/180242411/364067454-95500453-a799-46f1-b029-7156cdad7233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTEyMTgsIm5iZiI6MTcyNTQ1MDkxOCwicGF0aCI6Ii8xODAyNDI0MTEvMzY0MDY3NDU0LTk1NTAwNDUzLWE3OTktNDZmMS1iMDI5LTcxNTZjZGFkNzIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMTU1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDA5OWIyMGE3ZWU1ZGYxZTE4MzM0M2RjNzMyYmY1N2E2OThhYjE0YzFhYTQxYWQ4YTdmN2VlMDYzNTRmNzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CBAFnxHzVVmpYlwXy10WBAADtG5n31l5NV9yNorK89c)
> > 
> > 
> > **Perfect! thank you exactly what we needed to solve the issue!** Well it seems my script isn't the problem here: to solve your problem, **you have to install pip first**, it usually comes with last version of python (you also have to install python if you didn't do it yet of course) but you still can download it if you already have python installed **with the following command**: `py -m ensurepip --upgrade` Notice that on some Operating system it might be `python -m ensurepip --upgrade` or even `python3 -m ensurepip --upgrade` Please tell me if it works ;)
> 
> i have successfully installed all of the related requirements yet it still instantly closes when doing ./Start.bat ![image](https://private-user-images.githubusercontent.com/180242411/364401845-8a418a18-af45-4918-a4db-bed11f0a14d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjIwNTUsIm5iZiI6MTcyNTQ2MTc1NSwicGF0aCI6Ii8xODAyNDI0MTEvMzY0NDAxODQ1LThhNDE4YTE4LWFmNDUtNDkxOC1hNGRiLWJlZDExZjBhMTRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNDU1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmY4NjA0YjFjN2RhZDM5ZGMwNzdmZDNkMDZhZTM4ZTUwMjczMjg2NTRhMmEwZGRiNDhmZmYwOTZhYTk2OWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EZ5-tdSx77Iwr432FMt7No1xp8awKb1pi6avO7JjQmU) Perhaps there is another issue?

Okay it seems there is no error message unfortunately :/ Then you can try to different things: 
**Go in the _tarkov-map-tracker_ folder then open the terminal window and type:** `py gui.py` or `python gui.py`
There should be an error code (or maybe it'll start) tell me what happens! ^^
**If it does'nt work try to delete the _executed_previously.dat_ located in the _tarkov-map-tracker_ folder and then try again the first step I told you earlier in this message**

I hope we will be able to get either an error message or my software working

**Comment by sillyman6** [comment]
> > i have successfully installed all of the related requirements yet it still instantly closes when doing ./Start.bat ![image](https://private-user-images.githubusercontent.com/180242411/364401845-8a418a18-af45-4918-a4db-bed11f0a14d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjIwNTUsIm5iZiI6MTcyNTQ2MTc1NSwicGF0aCI6Ii8xODAyNDI0MTEvMzY0NDAxODQ1LThhNDE4YTE4LWFmNDUtNDkxOC1hNGRiLWJlZDExZjBhMTRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNDU1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmY4NjA0YjFjN2RhZDM5ZGMwNzdmZDNkMDZhZTM4ZTUwMjczMjg2NTRhMmEwZGRiNDhmZmYwOTZhYTk2OWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EZ5-tdSx77Iwr432FMt7No1xp8awKb1pi6avO7JjQmU) Perhaps there is another issue?
> 
> Okay it seems there is no error message unfortunately :/ Then you can try to different things: **Go in the _tarkov-map-tracker_ folder then open the terminal window and type:** `py gui.py` or `python gui.py` There should be an error code (or maybe it'll start) tell me what happens! ^^ **If it does'nt work try to delete the _executed_previously.dat_ located in the _tarkov-map-tracker_ folder and then try again the first step I told you earlier in this message**
> 
> I hope we will be able to get either an error message or my software working

thank you so much for your patience. it opened when typing "py gui.py" in the "D:\TarkovMapTracker-main\tarkov-map-tracker directory"

**Comment by M4elstr0m** [comment]
> > > i have successfully installed all of the related requirements yet it still instantly closes when doing ./Start.bat ![image](https://private-user-images.githubusercontent.com/180242411/364401845-8a418a18-af45-4918-a4db-bed11f0a14d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjIwNTUsIm5iZiI6MTcyNTQ2MTc1NSwicGF0aCI6Ii8xODAyNDI0MTEvMzY0NDAxODQ1LThhNDE4YTE4LWFmNDUtNDkxOC1hNGRiLWJlZDExZjBhMTRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNDU1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmY4NjA0YjFjN2RhZDM5ZGMwNzdmZDNkMDZhZTM4ZTUwMjczMjg2NTRhMmEwZGRiNDhmZmYwOTZhYTk2OWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EZ5-tdSx77Iwr432FMt7No1xp8awKb1pi6avO7JjQmU) Perhaps there is another issue?
> > 
> > 
> > Okay it seems there is no error message unfortunately :/ Then you can try to different things: **Go in the _tarkov-map-tracker_ folder then open the terminal window and type:** `py gui.py` or `python gui.py` There should be an error code (or maybe it'll start) tell me what happens! ^^ **If it does'nt work try to delete the _executed_previously.dat_ located in the _tarkov-map-tracker_ folder and then try again the first step I told you earlier in this message**
> > I hope we will be able to get either an error message or my software working
> 
> thank you so much for your patience. it opened when typing "py gui.py" in the "D:\TarkovMapTracker-main\tarkov-map-tracker directory"

Perfect ! ^^ so glad it worked I'll try to re-code the Batch.bat and update the repo ;) I'll send a message here when it'll be done! Have fun using my TarkovMapTracker ;)

**Comment by M4elstr0m** [comment]
Hey there everyone! I'm glad to announce I released the v1.0.1 in response to all the issues in this thread! Don't hesitate to download the v1.0.1 that (I believe) will be more convenient for every user!
If you are still encountering an issue with my software please create a new issue thread I'll be glad to help as soon as I can!
I updated the README.md with all the answers I wrote here but if you are stuck, don't hesitate to take a look at the previous messages like this one:

> @sillyman6 Okay it seems there is no error message unfortunately :/ Then you can try to different things: **Go in the _tarkov-map-tracker_ folder then open the terminal window and type:** `py gui.py` or `python gui.py` There should be an error code (or maybe it'll start) tell me what happens! ^^ **If it does'nt work try to delete the _executed_previously.dat_ located in the _tarkov-map-tracker_ folder and then try again the first step I told you earlier in this message**

Thanks everyone!
